### ISSUE TITLE
todo list (versions 2.1 - 2.5)

### ISSUE THREAD

**Issue by TezRomacH** [TezRomacH/DataKeeper#5]
- [ ] Write docs and wiki for version 2.1
- [ ] Rewrite `Unbind` (questions: should model use `SetActivity(false)` inside?)
- [ ] Update trigger's position with resorting set
- [ ] Create a NuGet package
- [ ] Make Constraints/Triggers unavailable out of the model (?)
- [ ] Add `SaveModel` and `LoadModel` to allow serialize the data in file
- [ ] Logging model (Log to console/file/string or no logging)
